# -*- coding: utf-8 -*-
"""projeto_grupo_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10FAjSYEckDW73Sl3zA3GNEQNzXm0YARJ

# Projeto: Fundamento de Machine Learning

**Professor:** Jorge Chamby-Diaz  
**Turma:** Caixaverso - Especialista em IA  
**Link grupos projeto:** [Planilha de grupos](https://docs.google.com/spreadsheets/d/1ixM0IRVW40Ptf7T4Q2qYt0NJbzcVoKAKWG5Zf5-Q1UQ/edit?usp=sharing)

<center><h3>Projeto Final - Fundamento de Machine Learning<h3></center>

**Descrição**  
Este notebook contém a descrição do projeto prático do módulo: Fundamento de Machine Learning. Neste projeto, os alunos deverão aplicar os conhecimentos aprendidos em aula, desde a análise exploratória até a construção de um modelo supervisionado, passando pela escolha do problema, estruturação da base, ajuste de hiperparâmetros e análise dos resultados.

**Objetivo**  
Realizar uma análise exploratória de dados e construir um modelo de Machine Learning supervisionado (classificação ou regressão) para resolver um problema real baseado em dados.

Sua análise deve conter um *storytelling*: uma história guiada por dados, gráficos, imagens e medidas estatísticas, que conduza o leitor desde o problema até a solução proposta. O projeto deve abordar um problema relevante encontrado na base escolhida, justificar por que ele é interessante e, a partir disso, construir um modelo preditivo com base em técnicas supervisionadas.  

Você está livre para utilizar quantas bases considerar necessário e filtrar as informações mais relevantes para sua história.

**Dados**  
Esta é uma lista de fontes que vocês podem utilizar. Outras fontes também são permitidas, desde que haja uma validação prévia com o professor.

#### Fontes de dados sugeridas:
- [Covid19br](https://github.com/wcota/covid19br/)
- [Agência Nacional de Petróleo e Gás](https://bit.ly/3hf8rbZ)
- [DataSUS (via FTP)](ftp.datasus.gov.br)
- [Dados.gov.br](https://bit.ly/3fPA1MO)
- [Kaggle](https://www.kaggle.com/)

> *Obs: Para acessar o FTP do DataSUS, utilize um cliente como o Filezilla.*

---

## Organização e entregáveis

- O projeto pode ser feito em grupo de até 05 participantes.  
- O projeto completo (notebook, código-fonte, links para fontes, bases e demais artefatos) deve ser:
  - Publicado no GitHub;
  - Enviado por e-mail (jchambyd@gmail.com), com nome dos participantes e link do repositório no GitHub.  
  - Assunto do e-mail: **Projeto Caixaverso - Fundamento de ML**

---

## Entregáveis esperados

- Análise exploratória de dados (EDA);
- Identificação de um problema relevante no(s) dataset(s) escolhido(s);
- Formulação do problema como uma tarefa de **classificação ou regressão**;
- Construção de um ou mais modelos de Machine Learning supervisionado;
- Avaliação comparativa dos modelos com **métricas adequadas**;
- Realização de **ajuste de hiperparâmetros**;
- Justificativa clara da escolha final do modelo;
- Visualizações e interpretações dos resultados.

---

## Critérios de Avaliação

A avaliação será feita com base nos artefatos entregues e na apresentação final do grupo.

### Apresentação
- Storytelling claro e objetivo;
- Identificação de padrões e insights na base de dados;
- Clareza na definição do problema e proposta de solução;
- Conclusões e recomendações.

### Técnicos
- EDA bem estruturada, incluindo:
  - Descrição das variáveis;
  - Dados faltantes;
  - Tipos de dados e limpeza da base;
- Análises univariadas e multivariadas;
  - Medidas estatísticas;
  - Gráficos e visualizações;
- Formulação e modelagem:
  - Definição do problema como tarefa de ML (classificação ou regressão);
  - Treinamento e avaliação de modelos;
  - Escolha da(s) métrica(s) de avaliação;
  - Ajuste de hiperparâmetros;
  - Reprodutibilidade do código.

### Comunicação
- Clareza na explicação do problema, da abordagem adotada e dos resultados obtidos;
- Boa organização do notebook e do repositório;
- Visualizações compreensíveis e informativas.

---

## Deadline
**Apresentação final:** 29/07/2025  
**Tempo estimado por grupo:** 15 ~ 20 minutos  
**Entrega via e-mail e GitHub:** até a véspera da apresentação

---

Boa sorte e mãos à obra! 🚀

# Trabalho Final - Grupo 1

## Informações Gerais

**Integrantes**
- Alexandre Ventrice (alexandre.ventrice@gmail.com)
- Diego Gustavo (costadiegus@gmail.com)
- Fábio Alves Braga (fabiobragasp@gmail.com)
- Paulo Donizetti (paulinhodgf@gmail.com)
- Rômulo Fuzo (romulo.fuzo@gmail.com)
- Waldir José Ferreira Jr (ferreirajrfarma@gmail.com)

Fonte: https://docs.google.com/spreadsheets/d/1ixM0IRVW40Ptf7T4Q2qYt0NJbzcVoKAKWG5Zf5-Q1UQ/edit?gid=0#gid=0

## Importações
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings("ignore")

"""## Carga de Dados"""

# CARGA DO DATASET DIRETO DO SITE DO KAGGLE
import os
from pathlib import Path

# 1. Autenticação: verifica se kaggle.json já existe
kaggle_path = Path("~/.kaggle/kaggle.json").expanduser()
if not kaggle_path.exists():
    from google.colab import files
    print("kaggle.json não encontrado. Faça o upload:")
    uploaded = files.upload()
    os.makedirs(kaggle_path.parent, exist_ok=True)
    (kaggle_path).write_bytes(uploaded["kaggle.json"])
    kaggle_path.chmod(0o600)
else:
    print("kaggle.json já está configurado.")

# 2. Instalar CLI do Kaggle (caso ainda não esteja)
!pip install -q kaggle

# 3. Baixar e extrair o dataset correto
!kaggle datasets download -d vagnerbessa/average-car-prices-bazil
!unzip -o average-car-prices-bazil.zip -d dataset/

# 4. Verificar os arquivos baixados
print("Arquivos na pasta 'dataset':", os.listdir("dataset"))

# Carregando o dataset
csv_path = 'dataset/fipe_cars.csv'
try:
    df = pd.read_csv(csv_path, encoding='latin1')
except FileNotFoundError:
    print(f"Arquivo '{csv_path}' não encontrado.")
    exit()

"""## Análise Exploratória de Dados"""

df.shape

df.head()

df.info()

df.describe()

import seaborn as sns
import matplotlib.pyplot as plt

# Calcula a correlação numérica
cor = df.corr(numeric_only=True)

# Reordena as colunas com base na correlação com 'avg_price_brl'
target_corr = cor['avg_price_brl'].abs().sort_values(ascending=False).index
cor_sorted = cor.loc[target_corr, target_corr]

# Heatmap centralizado na 'avg_price_brl'
sns.heatmap(cor_sorted, cmap='coolwarm', annot=False, center=0)
plt.title("Correlação entre variáveis ordenadas pela avg_price_brl")
plt.show()

# Cria DataFrame para usar 'hue'
target_corr = cor['avg_price_brl'].drop('avg_price_brl').sort_values(key=abs, ascending=False)
corr_df = target_corr.reset_index()
corr_df.columns = ['feature', 'correlation']

plt.figure(figsize=(8, 6))
sns.barplot(
    data=corr_df,
    x='correlation',
    y='feature',
    hue='correlation',
    palette='coolwarm',
    dodge=False,
    legend=False
)
plt.title("Correlação com a variável alvo: avg_price_brl")
plt.xlabel("Coeficiente de Correlação")
plt.ylabel("Variáveis")
plt.axvline(0, color='gray', linestyle='--')
plt.tight_layout()
plt.show()

sns.pairplot(df)

"""## Tratamento dos dados"""

# --- Verificação e Remoção de Linhas Duplicadas ---
print(f"Número de linhas antes de remover duplicatas: {len(df)}")

num_duplicates = df.duplicated().sum()
if num_duplicates > 0:
    print(f"Encontradas e removidas {num_duplicates} linhas duplicadas.")
    df.drop_duplicates(inplace=True)
else:
    print("Nenhuma linha duplicada encontrada.")

print(f"Número de linhas após remover duplicatas: {len(df)}")
print("-" * 30)

# Fuel e Gear
df_processed = df.copy()
df_processed = pd.get_dummies(df_processed, columns=['fuel', 'gear'], prefix=['fuel', 'gear'])

# Brand
le_brand = LabelEncoder()
df_processed['brand_encoded'] = le_brand.fit_transform(df_processed['brand'])
df_processed = df_processed.drop(['brand'], axis=1)

# Model
le_model = LabelEncoder()
df_processed['model_encoded'] = le_model.fit_transform(df_processed['model'])
df_processed = df_processed.drop(['model'], axis=1)

# Retirar colunas irrelevantes pro modelo
df_processed = df_processed.drop(['fipe_code', 'authentication', 'month_of_reference'], axis=1)

# Deletar colunas nulas caso existam
df_processed = df_processed.dropna()

df_processed.columns

display(df_processed)

"""## Modelagem"""

# --- Preparação dos Dados para o Modelo ---
X = df_processed.drop('avg_price_brl', axis=1)
y = df_processed['avg_price_brl']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Escalamos os dados para otimizar a Regressão Linear
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Treinamento e Avaliação do Modelo usando LinearRegression

l_regressor = LinearRegression()
l_regressor.fit(X_train_scaled, y_train)
y_pred_l_regressor = l_regressor.predict(X_test_scaled)

# Treinamento e Avaliação do Modelo usando DecisionTreeRegressor
dt_regressor = DecisionTreeRegressor(random_state=42)
dt_regressor.fit(X_train, y_train)
y_pred_dt_regressor = dt_regressor.predict(X_test)

# Treinamento e Avaliação do Modelo usando RandomForestRegressor
rf_regressor = RandomForestRegressor(random_state=42)
rf_regressor.fit(X_train, y_train)
y_pred_rf_regressor = rf_regressor.predict(X_test)

"""## Avaliação

### LinearRegression
"""

r2 = r2_score(y_test, y_pred_l_regressor)
mae = mean_absolute_error(y_test, y_pred_l_regressor)
mse = mean_squared_error(y_test, y_pred_l_regressor)
rmse = np.sqrt(mse)

print("\nResultados do Modelo Após Remoção de Duplicatas:")
print(f"R²: {r2:.3f}")
print(f"MAE: R$ {mae:,.2f}")
print(f"MSE: R$² {mse:,.2f}")
print(f"RMSE: R$ {rmse:,.2f}")

# --- Visualização ---
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred_l_regressor, alpha=0.5)
plt.title('Comparação Valor Real vs. Previsto (Dados Limpos)')
plt.xlabel('Valor Real (R$)')
plt.ylabel('Valor Previsto (R$)')
plt.grid(True)
max_val = max(y_test.max(), y_pred_l_regressor.max())
plt.plot([0, max_val], [0, max_val], 'r--')
plt.savefig('linear_prediction_no_duplicates.png')
plt.show()

# --- Criar um exemplo de carro para fazer a previsão ---
# Você pode alterar os valores neste dicionário para testar outros carros
car_example_data = {
    'year_of_reference': [2023], # Ano de referência da tabela FIPE
    'brand': ['GM - Chevrolet'],
    'model': ['ONIX HATCH 1.0 12V Flex 5p Mec.'],
    'fuel': ['Gasoline'],
    'gear': ['manual'],
    'engine_size': [1.0],
    'year_model': [2019] # Ano de fabricação do carro
}

car_df = pd.DataFrame(car_example_data)

print("Dados do carro para previsão:")
print(car_df)
print("-" * 30)

# --- Aplicar as mesmas transformações dos dados de treino ---
# É CRUCIAL usar os encoders já treinados (.transform) e não treinar de novo (.fit_transform)
car_df['brand_encoded'] = le_brand.transform(car_df['brand'])
car_df['model_encoded'] = le_model.transform(car_df['model'])

# Aplicar One-Hot Encoding
car_df = pd.get_dummies(car_df, columns=['fuel', 'gear'], prefix=['fuel', 'gear'])
car_df = car_df.drop(['brand', 'model'], axis=1)

# Alinhar as colunas do nosso exemplo com as colunas do modelo
# Isso garante que teremos todas as colunas do one-hot encoding, preenchendo com 0 as que não existem no exemplo
final_car_df = car_df.reindex(columns=X.columns, fill_value=0)


# --- Fazer a previsão ---
predicted_price = l_regressor.predict(final_car_df)

print(f"Preço PREVISTO para o carro: R$ {predicted_price[0]:,.2f}")

"""#### DecisionTreeRegressor"""

r2 = r2_score(y_test, y_pred_dt_regressor)
mae = mean_absolute_error(y_test, y_pred_dt_regressor)
mse = mean_squared_error(y_test, y_pred_dt_regressor)
rmse = np.sqrt(mse)

print("\nResultados do Modelo Após Remoção de Duplicatas:")
print(f"R²: {r2:.3f}")
print(f"MAE: R$ {mae:,.2f}")
print(f"MSE: R$² {mse:,.2f}")
print(f"RMSE: R$ {rmse:,.2f}")

# --- Visualização ---
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred_dt_regressor, alpha=0.5)
plt.title('Comparação Valor Real vs. Previsto (Dados Limpos)')
plt.xlabel('Valor Real (R$)')
plt.ylabel('Valor Previsto (R$)')
plt.grid(True)
max_val = max(y_test.max(), y_pred_dt_regressor.max())
plt.plot([0, max_val], [0, max_val], 'r--')
plt.savefig('decision_tree_prediction_no_duplicates.png')
plt.show()

# --- Criar um exemplo de carro para fazer a previsão ---
# Você pode alterar os valores neste dicionário para testar outros carros
car_example_data = {
    'year_of_reference': [2023], # Ano de referência da tabela FIPE
    'brand': ['GM - Chevrolet'],
    'model': ['ONIX HATCH 1.0 12V Flex 5p Mec.'],
    'fuel': ['Gasoline'],
    'gear': ['manual'],
    'engine_size': [1.0],
    'year_model': [2019] # Ano de fabricação do carro
}

car_df = pd.DataFrame(car_example_data)

print("Dados do carro para previsão:")
print(car_df)
print("-" * 30)

# --- Aplicar as mesmas transformações dos dados de treino ---
# É CRUCIAL usar os encoders já treinados (.transform) e não treinar de novo (.fit_transform)
car_df['brand_encoded'] = le_brand.transform(car_df['brand'])
car_df['model_encoded'] = le_model.transform(car_df['model'])

# Aplicar One-Hot Encoding
car_df = pd.get_dummies(car_df, columns=['fuel', 'gear'], prefix=['fuel', 'gear'])
car_df = car_df.drop(['brand', 'model'], axis=1)

# Alinhar as colunas do nosso exemplo com as colunas do modelo
# Isso garante que teremos todas as colunas do one-hot encoding, preenchendo com 0 as que não existem no exemplo
final_car_df = car_df.reindex(columns=X.columns, fill_value=0)


# --- Fazer a previsão ---
predicted_price = dt_regressor.predict(final_car_df)

print(f"Preço PREVISTO para o carro: R$ {predicted_price[0]:,.2f}")

"""#### RandomForestRegressor"""

r2 = r2_score(y_test, y_pred_rf_regressor)
mae = mean_absolute_error(y_test, y_pred_rf_regressor)
mse = mean_squared_error(y_test, y_pred_rf_regressor)
rmse = np.sqrt(mse)

print("\nResultados do Modelo Após Remoção de Duplicatas:")
print(f"R²: {r2:.3f}")
print(f"MAE: R$ {mae:,.2f}")
print(f"MSE: R$² {mse:,.2f}")
print(f"RMSE: R$ {rmse:,.2f}")

# --- Visualização ---
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred_rf_regressor, alpha=0.5)
plt.title('Comparação Valor Real vs. Previsto (Dados Limpos)')
plt.xlabel('Valor Real (R$)')
plt.ylabel('Valor Previsto (R$)')
plt.grid(True)
max_val = max(y_test.max(), y_pred_rf_regressor.max())
plt.plot([0, max_val], [0, max_val], 'r--')
plt.savefig('random_forest_prediction_no_duplicates.png')
plt.show()

# --- Criar um exemplo de carro para fazer a previsão ---
# Você pode alterar os valores neste dicionário para testar outros carros
car_example_data = {
    'year_of_reference': [2023], # Ano de referência da tabela FIPE
    'brand': ['GM - Chevrolet'],
    'model': ['ONIX HATCH 1.0 12V Flex 5p Mec.'],
    'fuel': ['Gasoline'],
    'gear': ['manual'],
    'engine_size': [1.0],
    'year_model': [2019] # Ano de fabricação do carro
}

car_df = pd.DataFrame(car_example_data)

print("Dados do carro para previsão:")
print(car_df)
print("-" * 30)

# --- Aplicar as mesmas transformações dos dados de treino ---
# É CRUCIAL usar os encoders já treinados (.transform) e não treinar de novo (.fit_transform)
car_df['brand_encoded'] = le_brand.transform(car_df['brand'])
car_df['model_encoded'] = le_model.transform(car_df['model'])

# Aplicar One-Hot Encoding
car_df = pd.get_dummies(car_df, columns=['fuel', 'gear'], prefix=['fuel', 'gear'])
car_df = car_df.drop(['brand', 'model'], axis=1)

# Alinhar as colunas do nosso exemplo com as colunas do modelo
# Isso garante que teremos todas as colunas do one-hot encoding, preenchendo com 0 as que não existem no exemplo
final_car_df = car_df.reindex(columns=X.columns, fill_value=0)


# --- Fazer a previsão ---
predicted_price = rf_regressor.predict(final_car_df)

print(f"Preço PREVISTO para o carro: R$ {predicted_price[0]:,.2f}")

"""### Ajuste de Hiperparâmetros"""

# Importações
!pip install scikit-optimize
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform
from skopt import BayesSearchCV
from skopt.space import Real, Integer, Categorical
from sklearn.tree import DecisionTreeRegressor

param_DecisionTree = {
    'max_features': ['sqrt', 'log2'], # Número de recursos a serem considerados para cada divisão
    'criterion': ['squared_error', 'friedman_mse'], # Função de avaliação da qualidade da divisão
    'splitter': ['best', 'random'] # Estratégia para escolher as divisões
}
param_RandomForest = {
    'n_estimators': [20, 25, 30],            # Número de árvores na floresta
    'max_features': ['sqrt', 'log2'] # Número de recursos a serem considerados ao procurar a melhor divisão
}
reg_DecisionTree = DecisionTreeRegressor(random_state=42)
reg_RandomForest = RandomForestRegressor(random_state=42)

"""#### GridSearchCV"""

# Verificar melhores HIPERPARAMETROS - GridSearchCV - DecisionTree
grid_search = GridSearchCV(reg_DecisionTree, param_DecisionTree, cv=5, verbose=3, scoring='neg_mean_absolute_error')
grid_search.fit(X, y)
print("Melhores parâmetros:", grid_search.best_params_)
print("Melhor MSE negativo:", abs(grid_search.best_score_))

"""Melhores parâmetros: {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'}
Melhor MSE negativo: 6252.434445084424
"""

# Verificar melhores HIPERPARAMETROS - GridSearchCV - RandomForest
grid_search = GridSearchCV(reg_RandomForest, param_RandomForest, cv=5, verbose=3, scoring='neg_mean_absolute_error')
grid_search.fit(X, y)
print("Melhores parâmetros:", grid_search.best_params_)
print("Melhor MSE negativo:", abs(grid_search.best_score_))

"""Melhores parâmetros: {'max_features': 'sqrt', 'n_estimators': 30}
Melhor MSE negativo: 6201.352139317452

#### RandomizedSearchCV
"""

# Verificar melhores HIPERPARAMETROS - RandomizedSearchCV - DecisionTree
random_search = RandomizedSearchCV(
    estimator=reg_DecisionTree,
    param_distributions=param_DecisionTree,
    n_iter=100,  # você pode ajustar para controlar tempo vs. cobertura
    scoring='neg_mean_squared_error',
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=3
)

random_search.fit(X_train, y_train)

print("Melhores parâmetros:", random_search.best_params_)
print("Melhor MSE negativo:", random_search.best_score_)

"""Melhores parâmetros: {'splitter': 'best', 'max_features': 'sqrt', 'criterion': 'friedman_mse'}
Melhor MSE negativo: -488511387.64851725
"""

# Verificar melhores HIPERPARAMETROS - RandomizedSearchCV - RandomForest
random_search = RandomizedSearchCV(
    estimator=reg_RandomForest,
    param_distributions=param_RandomForest,
    n_iter=50,  # você pode ajustar para controlar tempo vs. cobertura
    scoring='neg_mean_squared_error',
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=3
)

random_search.fit(X_train, y_train)

print("Melhores parâmetros:", random_search.best_params_)
print("Melhor MSE negativo:", random_search.best_score_)

"""Melhores parâmetros: {'n_estimators': 30, 'max_features': 'sqrt'}
Melhor MSE negativo: -361890718.26409256

#### BayesSearchCV
"""

# Verificar melhores HIPERPARAMETROS - BayesSearchCV - DecisionTree
opt = BayesSearchCV(
    estimator=reg_DecisionTree,
    search_spaces=param_DecisionTree,
    scoring='neg_mean_squared_error',
    n_iter=50,  # pode ajustar (mais = melhor mas mais lento)
    cv=5,
    n_jobs=-1,
    verbose=3,
    random_state=42
)

opt.fit(X_train, y_train)

print("Melhores parâmetros:", opt.best_params_)
print("Melhor MSE negativo:", opt.best_score_)

"""Melhores parâmetros: OrderedDict([('criterion', 'friedman_mse'), ('max_features', 'log2'), ('splitter', 'best')])
Melhor MSE negativo: -488511387.64851725
"""

# Verificar melhores HIPERPARAMETROS - BayesSearchCV - RandomForest
opt = BayesSearchCV(
    estimator=reg_RandomForest,
    search_spaces=param_RandomForest,
    scoring='neg_mean_squared_error',
    n_iter=50,  # pode ajustar (mais = melhor mas mais lento)
    cv=5,
    n_jobs=-1,
    verbose=3,
    random_state=42
)

opt.fit(X_train, y_train)

print("Melhores parâmetros:", opt.best_params_)
print("Melhor MSE negativo:", opt.best_score_)

"""Melhores parâmetros: OrderedDict([('max_features', 'sqrt'), ('n_estimators', 30)])
Melhor MSE negativo: -361890718.26409256

### Validação Cruzada
"""

from sklearn.model_selection import cross_validate, KFold
from sklearn.metrics import make_scorer

from sklearn.linear_model import ElasticNet

# Função reutilizada para validação cruzada
def plot_cv(estimator, X, y, n_splits, scoring):
    '''
    scoring: string relativa às métricas
    '''

    kf5 = KFold(n_splits=n_splits, shuffle=True, random_state=42)

    result_cv = cross_validate(estimator=estimator, X=X, y=y,
                               cv=kf5, scoring=scoring,
                               return_train_score=True)

    # ============================

    df_result_cv = pd.DataFrame(result_cv)
    df_result_cv = df_result_cv.abs()

    display(df_result_cv[["train_score", "test_score"]].describe())

    print("Diferença entre treino e teste")
    display((df_result_cv["train_score"] - df_result_cv["test_score"]).mean())

    # ============================

    print("\nDistribuição de métricas de treino:")
    sns.histplot(data=df_result_cv, x="train_score", kde=True)
    plt.show()

    print("\nDistribuição de métricas de teste:")
    sns.histplot(data=df_result_cv, x="test_score", kde=True)
    plt.show()

    print("\nAs duas juntas (compare a variância!):")
    sns.histplot(data=df_result_cv, x="train_score", kde=True)
    sns.histplot(data=df_result_cv, x="test_score", color="orange", kde=True)
    plt.show()

# Utilizar o Cross Validation para avaliar o desvio médio do modelo
en = DecisionTreeRegressor(max_depth= 20, min_samples_leaf= 1) # Já com o resultado do GridSearchCV

plot_cv(en, X, y, n_splits=30, scoring="neg_mean_absolute_error")

# Utilizar o Cross Validation para avaliar o desvio médio do modelo
en = RandomForestRegressor(max_features='log2', n_estimators=25) # Já com o resultado do GridSearchCV

plot_cv(en, X, y, n_splits=30, scoring="neg_mean_absolute_error")

"""**Conclusões**

O train_score estão muito próximos os valores, ou seja, não temos overfiting.
Se a diferença entre treino e teste for pequena (como é), então o modelo está estável, mas possivelmente subajustado (underfitting).
O desvio padrão dos scores entre as dobras (~500–600) mostra variação moderada, o que é aceitável.
O modelo parece consistente entre os diferentes subconjuntos de dados
"""